server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:weatherdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/WeatherService
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  threads:
    virtual:
      enabled: true

keycloak:
  clientId: "weather-api-client"

weatherstack:
  url: http://api.weatherstack.com/current?
  access-key: f3deb33cfcee21feb6e87b9d8a7f21eb

