version: '3.8'

services:
  keycloak:
    container_name: keycloak-dev
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - ./realm-config:/opt/keycloak/data/import